# Generated by Django 4.1 on 2023-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.TextField(max_length=11)),
                ('email', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=20)),
            ],
        ),
    ]
