# Generated by Django 4.1 on 2023-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
