# Generated by Django 4.1 on 2023-09-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_success_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='success',
        ),
    ]
