# Generated by Django 4.1 on 2023-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
        migrations.AddField(
            model_name='post',
            name='passwords',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
